apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codebootcamp-ingress
  labels:
    app.kubernetes.io/name: codebootcamp-ingress
spec:
  ingressClassName: nginx    
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api/sandbox"
        backend:
          service:
            name: sandbox-service
            port:
              number: 80
